# Generated by Django 5.2.4 on 2025-08-01 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_rename_message_messagemodel'),
        ('users', '0002_profile_mobile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='wishlist',
            field=models.ManyToManyField(blank=True, related_name='wishlisted_by', to='listings.property'),
        ),
    ]
