# Generated by Django 5.2.4 on 2025-08-01 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_wishlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='monthly_budget',
            new_name='budget',
        ),
    ]
