# Generated by Django 5.2.4 on 2025-08-03 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_rename_message_messagemodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messagemodel',
            options={'ordering': ['timestamp']},
        ),
        migrations.AddField(
            model_name='messagemodel',
            name='parent_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='listings.messagemodel'),
        ),
        migrations.AlterField(
            model_name='messagemodel',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='listings.property'),
        ),
    ]
